#   This file is part of the Ansel project.
#   Copyright (C) 2024 Aur√©lien PIERRE.
#   
#   Ansel is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   Ansel is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with Ansel.  If not, see <http://www.gnu.org/licenses/>.










blank_issues_enabled: true
contact_links:
  - name: Search Engine
    url: https://chantal.aurelienpierre.com
    about: Cross-search existing resources about Ansel, photography, color theory, etc. on software documentations, bug reports, forums and scientific papers.
  - name: Ansel Community Support
    url: https://community.ansel.photos/discussions-home
    about: Please ask and answer questions here.
  - name: Feature requests
    url: https://community.ansel.photos/discussions-category?category=6
    about: Ansel does not accept feature requests. To talk about your workflow problems, open a discussion on the community forum.
