name: flatpak-nightly

on:
  workflow_dispatch:

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ansel source
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 1
          fetch-tags: true
          submodules: true
      - name: Install Flatpak tools
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder jq

      - name: Build Flatpak
        env:
          MANIFEST_URL: https://raw.githubusercontent.com/aurelienpierreeng/ansel/refs/heads/master/packaging/flatpak/photos.ansel.ansel.json
        run: packaging/flatpak/build-flatpak.sh

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak
          path: build/flatpak/photos.ansel.app.flatpak
